# Pages project configuration
name = "gutter-portal-frontend"
compatibility_date = "2025-05-11"

[site]
bucket = "./dist"
entry-point = "functions"

[build]
command = "npm run build"
output_directory = "dist"

[env.production]
workers_dev = false
route = "portal.777.foo/*"

# Define the service binding
[env.production.services]
  [[env.production.services.bindings]]
  name = "API"
  service = "worker" # The name of your worker
