# In: 777lotto/portal/portal-bet/chat-worker/wrangler.toml

name = "chat-worker"
main = "src/index.ts"
account_id = "67d3a6021370e7b666fff2023b2db359"
compatibility_date = "2024-05-28"
compatibility_flags = [ "nodejs_compat_v2" ]

[site]
bucket = "../chat-frontend/dist"

[observability]
enabled = true
head_sampling_rate = 1


# --- REMOVE THE D1 CONFIG FROM THE TOP LEVEL ---
# [[d1_databases]]
# binding = "DB"
# database_name = "gutter_db"
# database_id = "3b81ffd2-e748-4750-b98a-7b8b4c058716"

# ===============================================================
#      DEVELOPMENT-SPECIFIC CONFIGURATION
# ===============================================================
[env.development]

# Development D1 binding
[[env.development.d1_databases]]
binding = "DB"
database_name = "gutter_db"
database_id = "3b81ffd2-e748-4750-b98a-7b8b4c058716"
migrations_dir = "../worker/migrations"

# ===============================================================
#      PRODUCTION-SPECIFIC CONFIGURATION
# ===============================================================
[env.production]
routes = [
  { pattern = "chat.777.foo/*", zone_name = "777.foo" }
]


# --- ADD THE D1 CONFIG TO THE PRODUCTION ENV ---
[[env.production.d1_databases]]
binding = "DB"
database_name = "gutter_db"
database_id = "3b81ffd2-e748-4750-b98a-7b8b4c058716"

# --- ADD THIS BLOCK FOR KV ---
[[env.production.kv_namespaces]]
binding = "CHAT_SESSIONS_PROD"
id = "7249042bdea841bd82796c90a5591a0c"
