name = "chat-worker"
main = "src/index.ts"
account_id = "67d3a6021370e7b666fff2023b2db359"
compatibility_date = "2024-05-28"
compatibility_flags = [ "nodejs_compat_v2" ]

# Bind to the same D1 database as your main worker
[[d1_databases]]
binding = "DB"
database_name = "gutter_db"
database_id = "3b81ffd2-e748-4750-b98a-7b8b4c058716"

[env.production]
# This sets up the subdomain
routes = [
  { pattern = "chat.777.foo/*", zone_name = "777.foo" }
]

[env.production.vars]
ENVIRONMENT = "production"
# You will get these from your Dyte account dashboard
# Add these secrets using `npx wrangler secret put ...`
# DYTE_ORG_ID = "..."
# DYTE_API_KEY = "..."
