# Configuration for the 'notification' worker
name = "notification"
main = "src/index.ts"
account_id = "67d3a6021370e7b666fff2023b2db359"
compatibility_date = "2024-05-28"
compatibility_flags = [ "nodejs_compat_v2" ]

# Observability settings for all environments
[observability]
enabled = true
head_sampling_rate = 1

# D1 Database binding for all environments
[[d1_databases]]
binding = "DB"
database_name = "gutter_db"
database_id = "3b81ffd2-e748-4750-b98a-7b8b4c058716"

# Queue consumer for all environments
[[queues.consumers]]
queue = "notifications"

# Development-specific variables
[vars]
EMAIL_FROM = "no-reply@777.foo"
SMS_FROM_NUMBER = "7706977777"
AWS_REGION = "us-east-2"


# ===============================================================
#      PRODUCTION-SPECIFIC CONFIGURATION
# ===============================================================
[env.production]

# Production-specific variables (inherits from top-level)
[env.production.vars]
ENVIRONMENT = "production"

# Production-specific D1 binding
[[env.production.d1_databases]]
binding = "DB"
database_name = "gutter_db"
database_id = "3b81ffd2-e748-4750-b98a-7b8b4c058716"

# Production-specific Queue consumer
[[env.production.queues.consumers]]
queue = "notifications"
