# Top-level configuration
name = "worker"
main = "src/index.ts"
account_id = "67d3a6021370e7b666fff2023b2db359"
compatibility_date = "2024-06-20"
compatibility_flags = [ "nodejs_compat_v2" ]

# Observability configuration (applies to all environments)
[observability]
enabled = true
head_sampling_rate = 1

# ===============================================================
#      DEVELOPMENT-SPECIFIC CONFIGURATION
# ===============================================================
[env.development]
# Development variables
[env.development.vars]
ENVIRONMENT = "development"
API_VERSION = "1.0.0"
PORTAL_URL = "http://localhost:5173/dashboard"

# Serve the frontend application from the /frontend/dist directory
[env.development.site]
bucket = "../frontend/dist"

[[env.development.d1_databases]]
binding = "DB"
database_name = "777pd1"
database_id = "4c83ab6f-3912-4e76-99f3-7d86d6cd6518"
migrations_dir = "./migrations"

# Development KV binding
[[env.development.kv_namespaces]]
binding = "TEMP_STORAGE"
id = "bbbd0ff333d14f2b8077226c79635395"
preview_id = "bbbd0ff333d14f2b8077226c79635395"

# Development service bindings
[[env.development.services]]
binding = "NOTIFICATION_SERVICE"
service = "notification"

[[env.development.services]]
binding = "PAYMENT_SERVICE"
service = "payment"

# Development queue binding
[[env.development.queues.producers]]
queue = "notifications"
binding = "NOTIFICATION_QUEUE"

# ===============================================================
#      PRODUCTION-SPECIFIC CONFIGURATION
# ===============================================================
[env.production]
# Route for production
routes = [
  { pattern = "portal.777.foo/*", zone_name = "777.foo" }
]

# Serve the frontend application from the /frontend/dist directory
[env.production.site]
bucket = "../frontend/dist"

[[env.production.d1_databases]]
binding = "DB"
database_name = "777pd1"
database_id = "4c83ab6f-3912-4e76-99f3-7d86d6cd6518"
migrations_dir = "./migrations"

# Production variables
[env.production.vars]
ENVIRONMENT = "production"
API_VERSION = "1.0.0"
PORTAL_URL = "https://portal.777.foo"

[env.production.secrets]
GOOGLE_API_KEY = "GOOGLE_API_KEY"

# Production KV binding
[[env.production.kv_namespaces]]
binding = "TEMP_STORAGE"
id = "bbbd0ff333d14f2b8077226c79635395"

# NOTE: We don't need to define the D1 database again here,
# as it will inherit the top-level definition.

[[env.production.services]]
binding = "NOTIFICATION_SERVICE"
service = "notification-production"

[[env.production.services]]
binding = "PAYMENT_SERVICE"
service = "payment-production"

# Production queue binding
[[env.production.queues.producers]]
queue = "notifications"
binding = "NOTIFICATION_QUEUE"
