# Top-level configuration
name = "worker"
main = "src/index.ts"
account_id = "67d3a6021370e7b666fff2023b2db359"
compatibility_date = "2024-06-20"
compatibility_flags = [ "nodejs_compat_v2" ]

# Serve the frontend application from the /frontend/dist directory
[site]
bucket = "../frontend/dist"

# Observability configuration (applies to all environments)
[observability]
enabled = true
head_sampling_rate = 1

# ===============================================================
#      DEVELOPMENT-SPECIFIC CONFIGURATION
# ===============================================================
[env.development]
# Development variables
[env.development.vars]
ENVIRONMENT = "development"
API_VERSION = "1.0.0"
PORTAL_URL = "http://localhost:5173/dashboard"

# Development Durable Object binding
[[env.development.durable_objects.bindings]]
name = "CUSTOMER_SUPPORT_CHAT"
class_name = "CustomerSupportChat"

# Development D1 binding
[[env.development.d1_databases]]
binding = "DB"
database_name = "gutter_db"
database_id = "3b81ffd2-e748-4750-b98a-7b8b4c058716"
migrations_dir = "./migrations"

# Development KV binding
[[env.development.kv_namespaces]]
binding = "TEMP_STORAGE"
id = "bbbd0ff333d14f2b8077226c79635395"
preview_id = "bbbd0ff333d14f2b8077226c79635395"

# Development service bindings
[[env.development.services]]
binding = "NOTIFICATION_SERVICE"
service = "notification"

[[env.development.services]]
binding = "PAYMENT_SERVICE"
service = "payment"

# Development queue binding
[[env.development.queues.producers]]
queue = "notifications"
binding = "NOTIFICATION_QUEUE"

# Development migrations
[[env.development.migrations]]
tag = "v1"
new_classes = ["CustomerSupportChat"]


# ===============================================================
#      PRODUCTION-SPECIFIC CONFIGURATION
# ===============================================================
[env.production]
# Route for production
routes = [
  { pattern = "portal.777.foo/*", zone_name = "777.foo" }
]

# Production Durable Object binding
[[env.production.durable_objects.bindings]]
name = "CUSTOMER_SUPPORT_CHAT"
class_name = "CustomerSupportChat"

# Production variables
[env.production.vars]
ENVIRONMENT = "production"
API_VERSION = "1.0.0"
PORTAL_URL = "https://portal.777.foo/dashboard"

[env.production.secrets]
GOOGLE_API_KEY = "GOOGLE_API_KEY"

# Production KV binding
[[env.production.kv_namespaces]]
binding = "TEMP_STORAGE"
id = "bbbd0ff333d14f2b8077226c79635395"

# Production D1 binding
[[env.production.d1_databases]]
binding = "DB"
database_name = "gutter_db"
database_id = "3b81ffd2-e748-4750-b98a-7b8b4c058716"
migrations_dir = "./migrations"

[[env.production.services]]
binding = "NOTIFICATION_SERVICE"
service = "notification-production"

[[env.production.services]]
binding = "PAYMENT_SERVICE"
service = "payment-production"

# Production queue binding
[[env.production.queues.producers]]
queue = "notifications"
binding = "NOTIFICATION_QUEUE"

# Production migrations
[[env.production.migrations]]
tag = "v1"
new_classes = ["CustomerSupportChat"]
