name: Deploy All Services

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy to Cloudflare
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest
          
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
        
      - name: Build shared package
        run: cd packages/shared && pnpm run build
        
      - name: Apply D1 Migrations
        run: |
          echo "Applying D1 migrations..."
          cd worker && npx wrangler d1 migrations apply gutter_db --env production
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        
      - name: Deploy Notification Worker  
        run: |
          echo "Deploying notification worker..."
          cd notification
          echo "Current directory: $(pwd)"
          echo "Files in directory: $(ls -la)"
          pnpm run deploy
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          
      - name: Deploy Payment Worker
        run: |
          echo "Deploying payment worker..."
          cd payment
          echo "Current directory: $(pwd)"
          echo "Files in directory: $(ls -la)"
          pnpm run deploy
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        
      - name: Deploy Main Worker
        run: |
          echo "Deploying main worker..."
          cd worker
          echo "Current directory: $(pwd)"
          echo "Files in directory: $(ls -la)"
          pnpm run deploy
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          
      - name: Deploy Frontend
        run: |
          cd frontend
          pnpm run build
          npx wrangler pages deploy dist --project-name=portal --compatibility-date=2025-04-21
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
